### ISSUE TITLE
Create a test.yml folder under `.github/workflows/test.yml`

### ISSUE THREAD

**Issue by hybridx** [VaishnaviMudaliar/my-first-github-action#2]
```
name: Testworkflow
on: 
  push:
    branches: 
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Say hello
        run: echo "Hello There"
```
